export const posterData = {
  a: {
    categoryId: 'A',
    categoryEn: 'Architecture, Software',
    categoryJp: 'アーキテクチャ・ソフトウェア',
    copy: 'うごかすちから',
    color: 'rgba(204,41,170)',
    imgPath: [
      './img/poster1.png',
      './img/poster2.png',
      './img/poster3.png',
      './img/poster4.png',
      './img/poster5.png',
      './img/poster6.png',
      './img/poster7.png',
      './img/poster8.png',
      './img/poster9.png',
      './img/poster10.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から<br>解析まで',
      '双方向化技術による<br>データベーススキーマの共存',
      'サイエンスによる知的<br>ものづくり教育プログラム',
      'プログラミング講義向け<br>Jupyter Notebook環境',
      'Notebookで賢く運用！<br>NIIの研究クラウド',
      '再構成可能デバイスを<br>使いやすくする研究',
      '漸進的型付け: <br>安全性と柔軟性を<br>両立するプログラミング言語',
      '不具合局所化のための<br>プログラムスペクトルの<br>可視化ならびに分析',
      '経路計画機能の<br>テスト・設定調整の<br>自動探索',
      '適切な「ぼかし」で、<br>ソフトウェアの<br>複雑さに挑む',
    ]
  },
  b: {
    categoryId: 'B',
    categoryEn: 'Computation, Logic, <br> Quantum information',
    categoryJp: '数理・論理・量子情報',
    copy: '考え方をかんがえる',
    imgPath: [
      './img/poster11.png',
      './img/poster12.png',
      './img/poster13.png',
      './img/poster14.png',
      './img/poster15.png',
      './img/poster16.png',
      './img/poster17.png',
      './img/poster18.png'

    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から解析まで',
      '双方向化技術によるデータベーススキーマの共存',
      'サイエンスによる知的ものづくり教育プログラム',
      'プログラミング講義向けJupyter Notebook環境',
      'Notebookで賢く運用！NIIの研究クラウド',
      '再構成可能デバイスを使いやすくする研究',
      '漸進的型付け: 安全性と柔軟性を<br>両立するプログラミング言語',
      '不具合局所化のための<br>プログラムスペクトルの可視化ならびに分析',
    ]
  },
  c: {
    categoryId: 'C',
    categoryEn: 'Artificial intelligence',
    categoryJp: '人工知能',
    copy: '計算機に思考させる',
    imgPath: [
      './img/poster01.png',
      './img/poster02.png',
      './img/poster03.png',
      './img/poster04.png',
      './img/poster05.png',
      './img/poster06.png',
      './img/poster07.png',
      './img/poster08.png',
      './img/poster09.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から解析まで',
      '双方向化技術によるデータベーススキーマの共存',
      'サイエンスによる知的ものづくり教育プログラム',
      'プログラミング講義向けJupyter Notebook環境',
      'Notebookで賢く運用！NIIの研究クラウド',
      '再構成可能デバイスを使いやすくする研究',
      '漸進的型付け: 安全性と柔軟性を<br>両立するプログラミング言語',
      '不具合局所化のための<br>プログラムスペクトルの可視化ならびに分析',
      '理論計算機科学入門：<br>有限と無限のあいだ ~ オートマトン理論を例に',
    ]
  },
  d: {
    categoryId: 'D',
    categoryEn: 'Visual, audio, media',
    categoryJp: '映像・音・メディア',
    copy: 'みる・きく・はなす・さがす',
    imgPath: [
      './img/poster1.png',
      './img/poster2.png',
      './img/poster3.png',
      './img/poster4.png',
      './img/poster5.png',
      './img/poster6.png',
      './img/poster7.png',
      './img/poster8.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から解析まで',
      '双方向化技術によるデータベーススキーマの共存',
      'サイエンスによる知的ものづくり教育プログラム',
      'プログラミング講義向けJupyter Notebook環境',
      'Notebookで賢く運用！NIIの研究クラウド',
      '再構成可能デバイスを使いやすくする研究',
      '漸進的型付け: 安全性と柔軟性を<br>両立するプログラミング言語',
      '不具合局所化のための<br>プログラムスペクトルの可視化ならびに分析',
    ]
  },
  e: {
    categoryId: 'E',
    categoryEn: 'Network, security',
    categoryJp: 'ネットワーク・セキュリティ',
    copy: '安心につながる',
    imgPath: [
      './img/poster01.png',
      './img/poster02.png',
      './img/poster03.png',
      './img/poster04.png',
      './img/poster05.png',
      './img/poster06.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から解析まで',
      '双方向化技術によるデータベーススキーマの共存',
      'サイエンスによる知的ものづくり教育プログラム',
      'プログラミング講義向けJupyter Notebook環境',
      'Notebookで賢く運用！NIIの研究クラウド',
      '再構成可能デバイスを使いやすくする研究',
    ]
  },
  f: {
    categoryId: 'F',
    categoryEn: 'Society and information',
    categoryJp: '社会と情報',
    copy: 'サイバー世界と<br>フィジカル世界の融合',
    imgPath: [
      './img/poster01.png',
      './img/poster02.png',
      './img/poster03.png',
      './img/poster04.png',
      './img/poster05.png',
      './img/poster06.png',
      './img/poster07.png',
      './img/poster08.png',
      './img/poster09.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から解析まで',
      '双方向化技術によるデータベーススキーマの共存',
      'サイエンスによる知的ものづくり教育プログラム',
      'プログラミング講義向けJupyter Notebook環境',
      'Notebookで賢く運用！NIIの研究クラウド',
      '再構成可能デバイスを使いやすくする研究',
      '漸進的型付け: 安全性と柔軟性を<br>両立するプログラミング言語',
      '不具合局所化のための<br>プログラムスペクトルの可視化ならびに分析',
      '理論計算機科学入門：<br>有限と無限のあいだ ~ オートマトン理論を例に',
    ]
  },
  s: {
    categoryId: '特別展示',
    categoryEn: 'Special Exhibition',
    categoryJp: 'サービス・事業含む',
    copy: '',
    imgPath: [
      './img/poster01.png',
      './img/poster02.png',
      './img/poster03.png',
      './img/poster04.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から解析まで',
      '双方向化技術によるデータベーススキーマの共存',
      'サイエンスによる知的ものづくり教育プログラム',
      'プログラミング講義向けJupyter Notebook環境',
    ]
  }
}
