export const posterData = {
  a: {
    categoryId: 'A',
    categoryEn: 'Architecture, Software',
    categoryJp: 'アーキテクチャ・ソフトウェア',
    copy: 'うごかすちから',
    imgPath: [
      './img/A01-sinetstream.png',
      './img/A02.png',
      './img/A03.png',
      './img/A04.png',
      './img/A05.png',
      './img/A06.png',
      './img/A07.png',
      './img/A08.png',
      './img/A00.png',
      './img/A10.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から<br>解析まで',
      '双方向化技術による<br>データベーススキーマの共存',
      'サイエンスによる知的<br>ものづくり教育プログラム',
      'プログラミング講義向け<br>Jupyter Notebook環境',
      'Notebookで賢く運用！<br>NIIの研究クラウド',
      '再構成可能デバイスを<br>使いやすくする研究',
      '漸進的型付け: <br>安全性と柔軟性を<br>両立するプログラミング言語',
      '不具合局所化のための<br>プログラムスペクトルの<br>可視化ならびに分析',
      '経路計画機能の<br>テスト・設定調整の<br>自動探索',
      '適切な「ぼかし」で、<br>ソフトウェアの<br>複雑さに挑む',
    ]
  },
  b: {
    categoryId: 'B',
    categoryEn: 'Computation, Logic, <br> Quantum information',
    categoryJp: '数理・論理・量子情報',
    copy: '考え方をかんがえる',
    imgPath: [
      './img/B01.png',
      './img/B02.png',
      './img/B03.png',
      './img/B04.png',
      './img/B05.png',
      './img/B06.png',
      './img/B07.png',
      './img/B08.png'

    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から解析まで',
      '双方向化技術によるデータベーススキーマの共存',
      'サイエンスによる知的ものづくり教育プログラム',
      'プログラミング講義向けJupyter Notebook環境',
      'Notebookで賢く運用！NIIの研究クラウド',
      '再構成可能デバイスを使いやすくする研究',
      '漸進的型付け: 安全性と柔軟性を<br>両立するプログラミング言語',
      '不具合局所化のための<br>プログラムスペクトルの可視化ならびに分析',
    ]
  },
  c: {
    categoryId: 'C',
    categoryEn: 'Artificial intelligence',
    categoryJp: '人工知能',
    copy: '計算機に思考させる',
    imgPath: [
      './img/C01.png',
      './img/C02.png',
      './img/C03.png',
      './img/C04.png',
      './img/C05.png',
      './img/C06.png',
      './img/C07.png',
      './img/C08.png',
      './img/C09.png',
      './img/C10.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から解析まで',
      '双方向化技術によるデータベーススキーマの共存',
      'サイエンスによる知的ものづくり教育プログラム',
      'プログラミング講義向けJupyter Notebook環境',
      'Notebookで賢く運用！NIIの研究クラウド',
      '再構成可能デバイスを使いやすくする研究',
      '漸進的型付け: 安全性と柔軟性を<br>両立するプログラミング言語',
      '不具合局所化のための<br>プログラムスペクトルの可視化ならびに分析',
      '理論計算機科学入門：<br>有限と無限のあいだ ~ オートマトン理論を例に',
      '視聴覚クロスモーダル検索の<br>ための共同埋め込みの学習'
    ]
  },
  d: {
    categoryId: 'D',
    categoryEn: 'Visual, audio, media',
    categoryJp: '映像・音・メディア',
    copy: 'みる・きく・はなす・さがす',
    imgPath: [
      './img/D01.png',
      './img/D02.png',
      './img/D03.png',
      './img/D04.png',
      './img/D05.png',
      './img/D06.png',
      './img/D07.png',
      './img/D08.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から解析まで',
      '双方向化技術によるデータベーススキーマの共存',
      'サイエンスによる知的ものづくり教育プログラム',
      'プログラミング講義向けJupyter Notebook環境',
      'Notebookで賢く運用！NIIの研究クラウド',
      '再構成可能デバイスを使いやすくする研究',
      '漸進的型付け: 安全性と柔軟性を<br>両立するプログラミング言語',
      '不具合局所化のための<br>プログラムスペクトルの可視化ならびに分析',
    ]
  },
  e: {
    categoryId: 'E',
    categoryEn: 'Network, security',
    categoryJp: 'ネットワーク・セキュリティ',
    copy: '安心につながる',
    imgPath: [
      './img/E01.png',
      './img/E02.png',
      './img/E03.png',
      './img/E04.png',
      './img/E05.png',
      './img/E06.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から解析まで',
      '双方向化技術によるデータベーススキーマの共存',
      'サイエンスによる知的ものづくり教育プログラム',
      'プログラミング講義向けJupyter Notebook環境',
      'Notebookで賢く運用！NIIの研究クラウド',
      '再構成可能デバイスを使いやすくする研究',
    ]
  },
  f: {
    categoryId: 'F',
    categoryEn: 'Society and information',
    categoryJp: '社会と情報',
    copy: 'サイバー世界と<br>フィジカル世界の融合',
    imgPath: [
      './img/F01.png',
      './img/F02.png',
      './img/F03.png',
      './img/F04.png',
      './img/F05.png',
      './img/F06.png',
      './img/F07.png',
      './img/F08.png',
      './img/F09.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から解析まで',
      '双方向化技術によるデータベーススキーマの共存',
      'サイエンスによる知的ものづくり教育プログラム',
      'プログラミング講義向けJupyter Notebook環境',
      'Notebookで賢く運用！NIIの研究クラウド',
      '再構成可能デバイスを使いやすくする研究',
      '漸進的型付け: 安全性と柔軟性を<br>両立するプログラミング言語',
      '不具合局所化のための<br>プログラムスペクトルの可視化ならびに分析',
      '理論計算機科学入門：<br>有限と無限のあいだ ~ オートマトン理論を例に',
    ]
  },
  s: {
    categoryId: '特別展示',
    categoryEn: 'Special Exhibition',
    categoryJp: 'サービス・事業含む',
    copy: '',
    imgPath: [
      './img/S01.png',
      './img/S02.png',
      './img/S03.png',
      './img/S04.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から解析まで',
      '双方向化技術によるデータベーススキーマの共存',
      'サイエンスによる知的ものづくり教育プログラム',
      'プログラミング講義向けJupyter Notebook環境',
    ]
  }
}
