export const posterData = {
  a: {
    categoryId: 'A',
    categoryEn: 'Architecture, Software',
    categoryJp: 'アーキテクチャ・ソフトウェア',
    copy: 'うごかすちから',
    imgPath: [
      './img/A01-sinetstream.png',
      './img/A02.png',
      './img/A03.png',
      './img/A04.png',
      './img/A05.png',
      './img/A06.png',
      './img/A07.png',
      './img/A08.png',
      './img/A09.png',
      './img/A10.png',
    ],
    posterTitle: [
      'ネットワークとクラウドを<br>活用してデータ収集から<br>解析まで',
      '双方向化技術による<br>データベーススキーマの共存',
      'サイエンスによる知的<br>ものづくり教育プログラム',
      'プログラミング講義向け<br>Jupyter Notebook環境',
      'Notebookで賢く運用！<br>NIIの研究クラウド',
      '再構成可能デバイスを<br>使いやすくする研究',
      '漸進的型付け: <br>安全性と柔軟性を<br>両立するプログラミング言語',
      '不具合局所化のための<br>プログラムスペクトルの<br>可視化ならびに分析',
      '経路計画機能の<br>テスト・設定調整の<br>自動探索',
      '適切な「ぼかし」で、<br>ソフトウェアの<br>複雑さに挑む',
    ]
  },
  b: {
    categoryId: 'B',
    categoryEn: 'Computation, Logic, Quantum information',
    categoryJp: '数理・論理・量子情報',
    copy: '考え方をかんがえる',
    imgPath: [
      './img/B01.png',
      './img/B02.png',
      './img/B03.png',
      './img/B04.png',
      './img/B05.png',
      './img/B06.png',
      './img/B07.png',
      './img/B08.png'

    ],
    posterTitle: [
      '理論計算機科学入門： <br>有限と無限のあいだ <br>~ オートマトン理論を例に',
      '量子の世界に潜むスケール<br>フリーネットワーク',
      '計算量理論と暗号の安全性',
      'Inner-iteration preconditioned <br>block GMRES',
      'ネットワークにおける頂点の<br>重要度の感度解析',
      '口コミ効果の最大化:<br>やってみよう!<br>ゲーム Infomania',
      '食品価格の時系列表現の<br>形式化',
      '数学からソフトウェア、<br>そしてものづくりへ',
    ]
  },
  c: {
    categoryId: 'C',
    categoryEn: 'Artificial intelligence',
    categoryJp: '人工知能',
    copy: '計算機に思考させる',
    imgPath: [
      './img/C01.png',
      './img/C02.png',
      './img/C03.png',
      './img/C04.png',
      './img/C05.png',
      './img/C06.png',
      './img/C07.png',
      './img/C08.png',
      './img/C09.png',
      './img/C10.png',
    ],
    posterTitle: [
      '医療ビッグデータクラウド<br>基盤構築とAI画像解析研究',
      '知識表現・推論と機械学習を統合<br>したロバストAI',
      'コンピュータが法律推論？',
      '機械読解における<br>質問回答ペアの生成モデル',
      '機械学習で知識発見',
      '機械学習の幾何学的解釈',
      'ロバストインテリジェンスを<br>社会的な課題解決に役立てる<br>ための応用技術に関する研究',
      'クラウド型VRによる対話型<br>知能ロボットのオンライン競技会',
      '視聴覚クロスモーダル検索のための<br>共同埋め込みの学習',
      '自然言語処理の実社会応用'
    ]
  },
  d: {
    categoryId: 'D',
    categoryEn: 'Visual, audio, media',
    categoryJp: '映像・音・メディア',
    copy: 'みる・きく・はなす・さがす',
    imgPath: [
      './img/D01.png',
      './img/D02.png',
      './img/D03.png',
      './img/D04.png',
      './img/D05.png',
      './img/D06.png',
      './img/D07.png',
      './img/D08.png',
    ],
    posterTitle: [
      '情報学データ資源の共同利用',
      'NTCIR Challenges',
      'セマンティック画像生成',
      '実空間と整合する３次元映像<br>メディアに向けた光線情報符号化',
      'ROIS-DS人文学オーブンデータ<br>共同利用センター',
      'デッサン時の視線解析に<br>基づく物体の質感構成要素<br>の抽出',
      '記憶に残る鑑賞体験のための<br>ガイドアプリ：みんぱく<br>ガイド@国立民族学博物館',
      'テレビアーカイブを用いた<br>視聴者の行動センシング',
    ]
  },
  e: {
    categoryId: 'E',
    categoryEn: 'Network, security',
    categoryJp: 'ネットワーク・セキュリティ',
    copy: '安心につながる',
    imgPath: [
      './img/E01.png',
      './img/E02.png',
      './img/E03.png',
      './img/E04.png',
      './img/E05.png',
      './img/E06.png',
    ],
    posterTitle: [
      'ネットワーク事前知識を<br>活用したSINETログ<br>データの因果解析',
      'サブ6GHz及びミリ波帯を<br>共用するBeyond 5G<br>ネットワークの為の<br>深層強化学習を活用した<br>アクセスポイント選択法',
      '時空間深層学習モデルによる<br>ネットワークトラフィックの補間推定',
      'マルチメディアセキュリティ・<br>プライバシー',
      'Deepfake Detection and <br>Segmentation',
      'Gait Anonymization Using <br>Deep Learning',
    ]
  },
  f: {
    categoryId: 'F',
    categoryEn: 'Society and information',
    categoryJp: '社会と情報',
    copy: 'サイバー世界とフィジカル世界の融合',
    imgPath: [
      './img/F01.png',
      './img/F02.png',
      './img/F03.png',
      './img/F04.png',
      './img/F05.png',
      './img/F06.png',
      './img/F07.png',
      './img/F08.png',
      './img/F09.png',
    ],
    posterTitle: [
      'ブロックチェーンの登場で<br>社会はどう変化するのか？',
      '',
      'ソフトウェア工学からみた<br>機械学習',
      '新型コロナウイルス感染症<br>対策への位置情報ビッグ<br>データの応用',
      'ネットワーク投票力指数：<br>株式保有ネットワークに<br>おける間接的支配の測定',
      '過積載を見逃さない道路橋',
      '料理レシピ：カーボンフット<br>プリントを改善するには？',
      'Flavorlens 2.0',
      'Early stress detection and <br>absenteeism reduction',
    ]
  },
  s: {
    categoryId: '特別展示',
    categoryEn: 'Special Exhibition',
    categoryJp: 'サービス・事業含む',
    copy: '',
    imgPath: [
      './img/S01.png',
      './img/S02.png',
      './img/S03.png',
      './img/S04.png',
    ],
    posterTitle: [
      '湘南会議',
      '国立情報学研究所の<br>広報活動を紹介',
      '情報学専攻の概要紹介と<br>入試案内',
      '学術情報基盤の整備',
    ]
  }
}
